name: ssl_pinning_plugin
description: SSL Pinning for request HTTP.
version: 1.2.0
author: Macif <contact.appmobile@macif.fr>
homepage: https://github.com/macif-dev/sslpinning_plugin

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.macif.plugin.sslpinningplugin
    pluginClass: SslPinningPlugin
